DefaultContentLanguage = "fr"
baseURL = ""
languageCode = "fr-ch"
title = "Mercredistes"

disableAliases = true
disableKinds = ["sitemap", "RSS", "taxonomy", "taxonomyTerm", "section"]
enableGitInfo = true
enableRobotsTXT = true
googleAnalytics = "G-CJ1RRBDH90"
# add redirects/headers
[outputs]
home = ["HTML", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
baseName = "_redirects"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true

[params]
description = "Liste des albums photos"
disallow_search_engines = true
theme_variant = "" # possible value for the theme_variant `cerulean,cosmo,cyborg,darkly,flatly,journal,litera,lumen,lux,materia,minty,pulse,sandstone,simplex,slate,solar,spacelab,superhero,united,yeti`

[caches]
[caches.getjson]
maxAge = "1h"
