[build]
    command = "hugo -b $URL --minify --enableGitInfo"
    publish = "public"
    functions = "functions"

[build.environment]
    HUGO_VERSION = "0.92.0"
    TZ = "Europe/Zurich"

[context.production.environment]
    HUGO_ENV = "production"
    NODE_ENV = "production"
    HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
    command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
    command = "hugo -b $DEPLOY_PRIME_URL"
